name: ort_memory
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  onnx_dart:
    path: plugins/onnx_dart
  package_info: ^2.0.2
  package_info_plus: ^8.1.0
  path_provider: ^2.1.4
  ua_client_hints: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
